#!/usr/bin/env node

var fs = require('fs');
var path = require('path');
var exec = require('exec');

var srcFile = path.normalize("resources/bubbla4-1-transp.png");
var destDir = path.normalize("config/android/res/");

if (!fs.existsSync(destDir)) {
	throw new Error("Directory does not exist: " + destDir);
}

if (!fs.existsSync(srcFile)) {
	throw new Error("Source file does not exist: " + srcFile);	
}

var icons = {
	"drawable/icon": 			"96x96",
	"drawable-hdpi/icon": 		"72x72",
	"drawable-mdpi/icon": 		"48x48",
	"drawable-xhdpi/icon": 		"96x96",
	"drawable-xxhdpi/icon": 	"144x144",
	"drawable-xxxhdpi/icon": 	"192x192"
};

Object.keys(icons).forEach(function (key) {
	var filename = key + ".png";
	var destFile = path.join(destDir, filename);
	var size = icons[key] + "\!";
	var command = ["convert", srcFile, "-resize", size, destFile];
	console.log(command.join(" "));
	exec(command, function (err, out, code) {
		if (err instanceof Error) {
			throw err;
		}
		process.stderr.write(err);
		process.stdout.write(out);
		if (code !== 0) {
			throw new Error ("Returned code " + code);
		}		
	});
});